#include<iostream>
using namespace std;
main()
{
float num1;
float num2;
float num3;
float num4;
float num5;
float num6;
float num7;
float num8;
float num9;
float num10;
float num11;
float num12;
float num13;
float num14;
float num15;
float add;
float sub;
float mul;
float total;
cout<<"Enter first number ";
cin>>num1;
cout<<"Enter second number ";
cin>>num2;
cout<<"Enter third number ";
cin>>num3;
cout<<"Enter fourth number ";
cin>>num4;
cout<<"Enter fifth number ";
cin>>num5;
cout<<"Enter seventh number ";
cin>>num7;
cout<<"Enter eighth number ";
cin>>num8;
cout<<"Enter ninth number ";
cin>>num9;
cout<<"Enter tenth number ";
cin>>num10;
cout<<"Enter eleventh number ";
cin>>num11;
cout<<"Enter twelvth number ";
cin>>num12;
cout<<"Enter thirteenth number ";
cin>>num13;
cout<<"Enter fouteenth number ";
cin>>num14;
cout<<"Enter fifteenth number ";
cin>>num15;
add=num1+num2+num3+num4+num5;
sub=num6-num7-num8-num9-num10;
mul=num11*num12*num13*num14*num15;
total=add+sub+mul;
cout<<"The sum of first five numbers is "<<add<<endl;
cout<<"The subtraction of next five numbers is "<<sub<<endl;
cout<<"The multiplication of last five numbers is "<<mul<<endl;
cout<<"Total is "<<total;
}
